### ISSUE TITLE
unable to pass boolean value in json object request params

### ISSUE THREAD

**Issue by rajeevprasanna** [hmil/RosHTTP#71]
Hi,
 I am trying to make an api call with json input. Error in passing boolean value in json object.

    val jsonData = JSONObject(
      "recursive" -> false,
      "path" -> ""
    )
There are no implicits available for conversion of boolean to JSONValue.

Is there any other way to pass json data with boolean ?

**Comment by hmil** [comment]
You are right, it seems like the boolean JSON type is missing. You could add it somewhere around [here](https://github.com/hmil/RosHTTP/blob/master/shared/src/main/scala/fr/hmil/roshttp/body/JSONBody.scala#L21) and then add the implicit conversion so that your usage above works out of the box.

PRs welcome
